# Generated by Django 5.0.1 on 2024-01-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=50)),
                ('foodAvailability', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('type', models.TextField()),
                ('contactNumber', models.IntegerField()),
                ('foodVarieties', models.TextField()),
                ('imagePath', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
